add/modify 10 crons

diff --git a/cron/lookahead-10 b/cron/lookahead-10
--- a/cron/lookahead-10
+++ b/cron/lookahead-10
@@ -3,7 +3,7 @@ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
 FROMMAIL="Compose Tracker <releng@rockylinux.org>"
 git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b r10s /etc/pungi-lh-10
 rm -rf /etc/pungi-lh-10
-pushd /etc/pungi-lh-10/scripts || { echo "Pungi directory not found"; exit; }
+pushd /etc/pungi-lh-10/scripts/compose || { echo "Pungi directory not found"; exit; }
 git pull
 ret_val=$?
 if [ "$ret_val" -ne 0 ]; then
diff --git a/cron/stable-10 b/cron/stable-10
--- a/cron/stable-10
+++ b/cron/stable-10
@@ -2,7 +2,7 @@
 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
 FROMMAIL="Compose Tracker <releng@rockylinux.org>"
 rm -rf /etc/pungi-prod-10
-pushd /etc/pungi-prod-10/scripts || { echo "Pungi directory not found"; exit; }
+pushd /etc/pungi-prod-10/scripts/compose || { echo "Pungi directory not found"; exit; }
 git pull
 ret_val=$?
 if [ "$ret_val" -ne 0 ]; then
