update scripts

diff --git a/cron/lookahead-10 b/cron/lookahead-10
--- a/cron/lookahead-10
+++ b/cron/lookahead-10
@@ -1,19 +1,20 @@
 #!/bin/bash
 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
 FROMMAIL="Compose Tracker <releng@rockylinux.org>"
-git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b r10s /etc/pungi-lh-10
-rm -rf /etc/pungi-lh-10
-pushd /etc/pungi-lh-10/scripts/compose || { echo "Pungi directory not found"; exit; }
-git pull
+export RLVER=10
+source "/root/toolkit/sync/common"
+rm -rf /etc/pungi-lh-${MAJOR}
+git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b r${RLVER}s /etc/pungi-lh-${MAJOR}
 ret_val=$?
 if [ "$ret_val" -ne 0 ]; then
   echo "Git pull failed for LookAhead pungi config" | mutt -e "set from=\"$FROMMAIL\"" \
     -e 'set envelope_from=yes' \
-    -s "Git pull on /etc/pungi-lh-10 failed" \
+    -s "Git pull on /etc/pungi-lh-${MAJOR} failed" \
     releng@rockylinux.org
   exit 1
 fi
-bash produce-10-lookahead-full.sh
+pushd /etc/pungi-lh-${MAJOR}/scripts/compose || { echo "Pungi directory not found"; exit; }
+bash produce-${MAJOR}-lookahead-full.sh
 ret_val=$?
 popd || { echo "Could not go back to the previous directory"; exit; }
 
diff --git a/cron/stable-10 b/cron/stable-10
--- a/cron/stable-10
+++ b/cron/stable-10
@@ -1,18 +1,20 @@
 #!/bin/bash
 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
 FROMMAIL="Compose Tracker <releng@rockylinux.org>"
+export RLVER=10
+source "/root/toolkit/sync/common"
 rm -rf /etc/pungi-prod-10
-pushd /etc/pungi-prod-10/scripts/compose || { echo "Pungi directory not found"; exit; }
-git pull
+git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b r${REVISION} /etc/pungi-prod-${MAJOR}
 ret_val=$?
 if [ "$ret_val" -ne 0 ]; then
-  echo "Git pull failed for LookAhead pungi config" | mutt -e "set from=\"$FROMMAIL\"" \
+  echo "Git pull failed for pungi config" | mutt -e "set from=\"$FROMMAIL\"" \
     -e 'set envelope_from=yes' \
-    -s "Git pull on /etc/pungi-prod-10 failed" \
+    -s "Git pull on /etc/pungi-prod-${MAJOR} failed" \
     releng@rockylinux.org
   exit 1
 fi
-bash produce-10-full.sh
+pushd /etc/pungi-prod-${MAJOR}/scripts/compose || { echo "Pungi directory not found"; exit; }
+bash produce-${MAJOR}-full.sh
 ret_val=$?
 popd || { echo "Could not go back to the previous directory"; exit; }
 
diff --git a/cron/stable-updates-10 b/cron/stable-updates-10
--- a/cron/stable-updates-10
+++ b/cron/stable-updates-10
@@ -3,18 +3,18 @@ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
 FROMMAIL="Compose Tracker <releng@rockylinux.org>"
 export RLVER=10
 source "/root/toolkit/sync/common"
-rm -rf /etc/pungi-prod-10
-git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b "r${REVISION}" /etc/pungi-prod-10
+rm -rf /etc/pungi-prod-${MAJOR}
+git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b "r${REVISION}" "/etc/pungi-prod-${MAJOR}"
 ret_val=$?
 if [ "$ret_val" -ne 0 ]; then
   echo "Git pull failed for prod pungi config" | mutt -e "set from=\"$FROMMAIL\"" \
     -e 'set envelope_from=yes' \
-    -s "Git pull on /etc/pungi-prod failed" \
+    -s "Git pull on /etc/pungi-prod-${MAJOR} failed" \
     releng@rockylinux.org
   exit 1
 fi
-pushd /etc/pungi-prod-10/scripts/compose || { echo "Cron: Failed to change directory"; exit 1; }
-bash updates-10-full.sh
+pushd /etc/pungi-prod-${MAJOR}/scripts/compose || { echo "Cron: Failed to change directory"; exit 1; }
+bash updates-${MAJOR}-full.sh
 ret_val=$?
 popd || { echo "Cron: Could not change back to original directory"; exit 1; }
 
@@ -26,7 +26,7 @@ if [ "$ret_val" -eq 0 ]; then
   popd || { echo "Cron: Could not change back to original directory"; exit 1; }
 
   # HighAvailability has no errata in the API at this time
-  pushd /mnt/repos-staging/mirror/pub/rocky/${REVISION} || { echo "Cron: Directory doesn't exist"; exit 1; }
+  pushd "/mnt/repos-staging/mirror/pub/rocky/${REVISION}" || { echo "Cron: Directory doesn't exist"; exit 1; }
   python3 /usr/local/bin/apollo_tree -p $(pwd) \
     -n 'Rocky Linux' \
     --major-version 10 \
diff --git a/cron/stable-updates-9 b/cron/stable-updates-9
--- a/cron/stable-updates-9
+++ b/cron/stable-updates-9
@@ -3,20 +3,20 @@ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
 FROMMAIL="Compose Tracker <releng@rockylinux.org>"
 export RLVER=9
 source "/root/toolkit/sync/common"
-rm -rf /etc/pungi-prod-9
-git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b "r${REVISION}" /etc/pungi-prod-9
+rm -rf /etc/pungi-prod-${MAJOR}
+git clone https://git.rockylinux.org/rocky/pungi-rocky.git -b "r${REVISION}" "/etc/pungi-prod-${MAJOR}"
 rm -rf /mnt/compose/9_metadata
 git clone https://git.rockylinux.org/rocky/rocky-module-metadata.git -b r9 /mnt/compose/9_metadata
 ret_val=$?
 if [ "$ret_val" -ne 0 ]; then
   echo "Git pull failed for prod pungi config" | mutt -e "set from=\"$FROMMAIL\"" \
     -e 'set envelope_from=yes' \
-    -s "Git pull on /etc/pungi-prod failed" \
+    -s "Git pull on /etc/pungi-prod-${MAJOR} failed" \
     releng@rockylinux.org
   exit 1
 fi
-pushd /etc/pungi-prod-9/scripts/compose || { echo "Cron: Failed to change directory"; exit 1; }
-bash updates-9-full.sh
+pushd /etc/pungi-prod-${MAJOR}/scripts/compose || { echo "Cron: Failed to change directory"; exit 1; }
+bash updates-${MAJOR}-full.sh
 ret_val=$?
 popd || { echo "Cron: Could not change back to original directory"; exit 1; }
 
